### PR TITLE
Adds afterpack script to flip EnableCookieEncryption electon fuse on

### LINKED ISSUE #1021: Enable cookieEncryption fuse for electron
**Is your feature request related to a problem? Please describe.**

At the moment, cookies for teams-for-linux (access tokens etc) are stored in plain-text in a sqllite db on disk, this is the default for electron.

**Describe the solution you'd like**

Enable the cookieEncryption fuse to make use of the built-in cookie encryption option.

https://www.electronjs.org/docs/latest/tutorial/fuses#cookieencryption

**Additional context**

The official MS Teams client had similar issues, which have since been mitigated.

https://www.vectra.ai/blog/undermining-microsoft-teams-security-by-mining-tokens

### PR DESCRIPTION
**Pull request by anguswilliams**
Closes #1021

### CODE REVIEW

**Comment by IsmaelMartinez** [comment]
Hi @anguswilliams , can you increase the lower number int he package.json file? https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/package.json#L3 To 1.3.23

I will need to wait until Monday (or at least sunday) to release, as there is a pre-release open. Thanks!

**Comment by anguswilliams** [comment]
Thanks @IsmaelMartinez, version bumped.

**Comment by IsmaelMartinez** [comment]
pre-released in here https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.3.23

**Comment by anguswilliams** [comment]
Thanks @IsmaelMartinez, whats the process for promoting out of pre-release?

**Comment by IsmaelMartinez** [comment]
Manually. I just promote it as soon as people are happy with it working. Hopefully this week. (Sorry, I have been on holidays)

**Comment by IsmaelMartinez** [comment]
apologies, I have been away for a while. This is now released.

**Comment by IsmaelMartinez** [comment]
apologies, I have been away for a while. This is now released.

**Pull request merged**
