### PR TITLE
Fixes #987

### LINKED ISSUE #987: Enhance zooming in and out controls
1. Since zooming in is `ctrl` and `+` key and `+` needs `shift` on many keyboard layouts so it make effectively` ctrl` + `shift` + `+` key for zoom in but only `ctrl` in case of zoom out. need to be consistent and make it work with or without `shift` like in real browsers
2. When reaching zoom limits (min or max) it visually stop zooming in/out but the actual zoom level keep on decreasing/increasing make it hard to recover from it unless you press `ctrl` + `0` or press the corresponding opposite key multiple times. so need to stop the zoom level when reaching the min/max
3. Add mouse wheel support for zooming in and out

### PR DESCRIPTION
**Pull request by mahmoudbahaa**
1) make control and key zooming work with or without shift. 
2) added mouse wheel scrolling
3) made a mimum and maximum for setting zoom level

#987

### CODE REVIEW

**Comment by jijojosephk** [comment]
@mahmoudbahaa Unfortunately, this change is not working for me. @IsmaelMartinez can you check once?

**Comment by IsmaelMartinez** [comment]
@jijojosephk, I dunno when I will have time to look at this. I wonder @mahmoudbahaa if it is because now is not calling the electron backend 

https://github.com/IsmaelMartinez/teams-for-linux/pull/988/files#diff-fca4883998b4adbfa81ab4b8580ee345d3240657aaf5de79a8433bf97d0885d1L27

When we implemented this, ages ago, we had to use the electron call but I don't remember the reasons behind it.

**Comment by IsmaelMartinez** [comment]
I am going to wait probably until tomorrow to ensure the other pre-release had a bit of time to be tested. Thanks again for your work!

**Comment by jijojosephk** [comment]
@IsmaelMartinez This had problems I was waiting for @mahmoudbahaa to comeback.

**Comment by IsmaelMartinez** [comment]
https://github.com/IsmaelMartinez/teams-for-linux/issues/987#issuecomment-1810365637 Harridu did test it and he seem happy. Is a pre-release, if we see people complaining we can revert the changes. (not idea but git is for that).

I will revert the snap release as to avoid impacting many people during the weekend.

**Comment by IsmaelMartinez** [comment]
By the way, can you be a bit more specific, @jijojosephk ? What didn't work? I might be able to test in the macOS version on Monday

**Comment by IsmaelMartinez** [comment]
Hi @jijojosephk , I have test it in MacOS and I can confirm it only works in the newer version of teams. The old version doesn't break so I think that is an ok compromise. I will mark it as released and do the next pre-release

**Pull request merged**
