### PR TITLE
Adding frame config option and removing electron remote library

### LINKED ISSUE #1444: Hide Title Bar
**Is your feature request related to a problem? Please describe.**
I'm trying to hide the title-bar in liinux, I know it's possible using electron, just can't find it in this app.
I also know there's an older issue on this topic - but doesn't seem to work properly [issue](https://github.com/IsmaelMartinez/teams-for-linux/issues/185)

**Describe the solution you'd like**
Have a flag in the configuration to activate it the "frame: false" option in electron when creating the window

Thanks!

### LINKED ISSUE #1468: Deb package for Amd64 has doubled in size
**Describe the bug**
teams-for-linux_1.11.3_amd64.deb is 187 MB.
teams-for-linux_1.11.2_amd64.deb was 85.4 MB.
Older packages always had more or less the same size.
Other packages have retained the size, but this one has more than doubled. Same for AppImage and tar.gz.

**Additional context**
Sorry if it's intentional or necessary, I just thought something might be redundant in the packages.

### PR DESCRIPTION
**Pull request by IsmaelMartinez**
* Adding frame config option to allow for frameless windows. Closes #1444
* Remove @electron/remote as I believe is not in use.

### CODE REVIEW

**Comment by Shadowfury22** [comment]
Uhmm... shouldn't this have a default value of "true" instead of "false"?
`			frame: {
				default: false,
				describe: 'Specify false to create a Frameless Window. Default is true',
				type: 'string'
			},
`
I got jumpscared by the lack of title bar after updating to 1.11.4 😅

**Comment by IsmaelMartinez** [comment]
Me bad... I really need some holidays. I will fix it later today and
probably release it in a new pre-release. Thanks for reporting it!

**Comment by IsmaelMartinez** [comment]
ok, https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.11.5 should have that as a optional option, not the default. Thanks again for reporting it!

**Comment by palves** [comment]
https://github.com/IsmaelMartinez/teams-for-linux/blob/main/app/config/README.md still reads "false" in the "Default Value" (third) column:

  frame	Specify false to create a Frameless Window. Default is true	false

I would suggest fixing that column's value, and dropping the "Default is true" sentence completely from the second column, as it is redundant.

**Comment by IsmaelMartinez** [comment]
yep, it looks like a bug. I will see when i can have a look but I think is just the type that is incorrect as described in here https://github.com/IsmaelMartinez/teams-for-linux/issues/1444#issuecomment-2587408486 . Apologies as I have been away due personal family reasons.

**Pull request merged**
