### PR TITLE
Better handle external requests in new windows

### LINKED ISSUE #182: Open actions from cards in system browser window
When there is an action in a card (like those posted by Jira, Jenkins and other connectors) 
image
and user clicks the action button (regardless if with Ctrl or without), a new Electron window is opened without a URL bar: 
image

Ideally a system browser window should be opened, but at least heaving a URL bar would be a workaround to manually copy the URL. 

I believe some work in this direction has been done by @HarlemSquirrel in https://github.com/HarlemSquirrel/teams-for-linux/commits/external-requests-made-by-js, but the pull request was not merged, I guess...

### PR DESCRIPTION
**Pull request by HarlemSquirrel**
Here we use a counter to track the requests that are slated to open in a new window and have a URL of `about:blank`. We then filter all requests and proceed normally when the counter is less than 1.

Closes #182

### CODE REVIEW

**Comment by IsmaelMartinez** [comment]
That sound like a possible solution. There might be a corner case when people sending links as you are clicking a link (so something to test) but I suspect it should be fairly safe! Sound! I will see if I can get some time to test it this week. :)

**Comment by HarlemSquirrel** [comment]
I've been running this all day with no issues so far.

**Comment by IsmaelMartinez** [comment]
Great! I just merge it to develop so snap -edge people can test it. I will be running it tomorrow and see when I got time to do another release. Thanks a lot again!!

**Comment by IsmaelMartinez** [comment]
just pre-released 0.6.6 so people that don't use snap can test it also. 
https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v0.6.6

**Pull request merged**
