### PR TITLE
Add electron spell checker option

### PR DESCRIPTION
**Pull request by humbertaco**
As mentioned in [this issue](https://github.com/IsmaelMartinez/teams-for-linux/issues/385#issuecomment-1378521745), I've added a new flag/option named `spellCheckerLanguages` with type array. This array will contain the language codes that we want to use for the spell checking offered by Electron. This is enabled only if the option is passed when running teams-for-linux.

### CODE REVIEW

**Comment by IsmaelMartinez** [comment]
Hi @humbertaco , thanks for contributing. 

If you can also add that option into the[ README](https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/README.md) file in the config folder that would be great. Otherwise the options are a bit hidden for the non coders.

Also, if you can increase the version number in [package.json](https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/package.json#L3) file to 1.0.48. Like that we release a new version with this change. 

Thanks again!!

**Comment by jijojosephk** [comment]
@humbertaco thanks for your efforts. One code quality issue has been added. The length of the function on onAppReady is increased. Could you please fix that?

If you're editing through vs-code, please use this extension.
image

**Comment by humbertaco** [comment]
Hi @jijojosephk, just did some refactoring to avoid such issue. I moved all the configuration related code to a dedicated function so the complexity would remain low. Let me know if you notice something else.

**Comment by jijojosephk** [comment]
> Hi @jijojosephk, just did some refactoring to avoid such issue. I moved all the configuration related code to a dedicated function so the complexity would remain low. Let me know if you notice something else.

Thank you. There was a merge conflict. Just resolved. Will be merged soon. Thanks a lot.

**Pull request merged**
