### PR TITLE
Add followSystemTheme config option

### PR DESCRIPTION
**Pull request by benterova**
- New command line option `--followSystemTheme`. Defaults to false.
- When following system theme, set Teams theme to the current light/dark setting after a small delay on startup. (2.5 seconds, if you attempt to do this too soon Teams freaks out and only updates the outer window with the new theme)
- Update Teams light/dark theme to match system theme when the system theme is changed.

### CODE REVIEW

**Comment by jijojosephk** [comment]
@benterova thanks for your efforts :heart:  could you update the `package.json` with version number? I think, it would be `1.4.6`

**Comment by benterova** [comment]
> @benterova thanks for your efforts ❤️ could you update the `package.json` with version number? I think, it would be `1.4.6`

Done :smile: Let me know if there's anything else that needs to be done!

**Comment by jijojosephk** [comment]
@benterova sorry, there was a merge in between. Can you sync your fork and update once again please? The version was changed to `1.4.6` already.

**Comment by benterova** [comment]
> @benterova sorry, there was a merge in between. Can you sync your fork and update once again please? The version was changed to `1.4.6` already.

Updated again

**Comment by jijojosephk** [comment]
@benterova it shows merge conflict. I guess you have to sync your fork and push again.

**Comment by jijojosephk** [comment]
Thanks @benterova. I fixed the conflict and merged. Thanks again! I'm sure the community will be very happy about this new addition.

**Pull request merged**
