### PR TITLE
Cover #162 , adding documentation related with camera feature in Snap

### PR DESCRIPTION
**Pull request by julian-alarcon**

### CODE REVIEW

**Comment by IsmaelMartinez** [comment]
Maybe worth adding it into the snapstore? Thanks for the contribution!

**Comment by IsmaelMartinez** [comment]
Thanks for adding the image! I hope helps people.

**Comment by julian-alarcon** [comment]
I updated Snap Store description and added the image to describe where is the option to enable the camera.
https://snapcraft.io/teams-for-linux/

**Comment by IsmaelMartinez** [comment]
related to #162

**Pull request merged**
