### PR TITLE
wip trying to fix screensharing

### PR DESCRIPTION
**Pull request by IsmaelMartinez**
probably lots of this stuff is not needed for the fix but I added most of the appConfig changes just to test them. Needs a proper cleanup but as the screensharing isn't working it can probably go in and see exactly what it brings at a later stage.

Apologies for the mess... not time for much better.

### CODE REVIEW

**Comment by pramodbutte** [comment]
I currently have snap store version installed? how do I get access to this version (for use . testing?)

**Comment by IsmaelMartinez** [comment]
Once it gets into the develop branch, you will be able to get it in the edge channel.

**Comment by IsmaelMartinez** [comment]
@pramodbutte , I am going to merge this into develop now. It should be in snap edge with version 0.4.3. If you can test it that will be more than appreciated.

**Comment by pramodbutte** [comment]
the snap edge is still at 4.2.  I will keep refreshing/ checking. thanks

**Comment by pramodbutte** [comment]
Ah needed to reboot the laptop to refresh snap store, but I can confirm it works.

**Comment by IsmaelMartinez** [comment]
thanks for testing it. Releasing soon then.

**Pull request merged**
