### PR TITLE
upgrade depencencies

### PR DESCRIPTION
**Pull request by IsmaelMartinez**

### CODE REVIEW

**Comment by IsmaelMartinez** [comment]
I can't test this in linux so will appreciate if someone can do it before I break 1000's of computers :D

**Comment by r-cdriscoll** [comment]
@IsmaelMartinez - I cloned the feat-upgrade-dependencies branch and ran via `yarn start` and it at least launched successfully and I was able to start a meeting, chat worked, and was able to access settings.  The only messages that were output in the terminal were:

```
[120300:1214/094551.337527:ERROR:nss_util.cc(349)] After loading Root Certs, loaded==false: NSS error code: -8018
[120342:1214/094706.003921:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: RED_8, share_between_threads: 0, gmb_type: shared_memory
[120342:1214/094706.004024:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: RG_88, share_between_threads: 0, gmb_type: shared_memory
```
but those might be specific to my setup?

Running Ubuntu 22.04.1, GNOME, x11, PipeWire, amd64

**Comment by IsmaelMartinez** [comment]
Thanks @r-cdriscoll , I will leave it open for a bit longer as I can't get it to work in my build, so wonder if it will break snap edge(that gets released automatically to a few thousands of people.

**Comment by MichalKoziorowski-TomTom** [comment]
@IsmaelMartinez Not everything is working when I built & installed deb package on Ubuntu 22.04 + wayland + PipeWire + amd64. Teams-for-linux started correctly but crashes when I try to share screen. Everything was ok in previously released deb.

**Comment by IsmaelMartinez** [comment]
well, did well to wait. I think we can wait until node 22.0.1 is out... or 22.0.2

**Comment by jijojosephk** [comment]
'22.0.3' breaks tray icon.

**Comment by jijojosephk** [comment]
Should this be merged @IsmaelMartinez ?

**Pull request closed without merging**
