### PR TITLE
fix(Intune): correctly iterate when ssoInTuneAuthUser is provided

### PR DESCRIPTION
**Pull request by fmoessbauer**
We need to iterate the values, not the indexes.

closes: #1466

### CODE REVIEW

**Comment by IsmaelMartinez** [comment]
Thanks a lot for contributing! I will create a pre-release and see if people can have a play with it. 1.2.1 has an annoying screensharing issue for some people, if we see this also happens to you I can try to do a 1.11.6 release with your changes.

Thanks again for the fix!

**Comment by nsballmann** [comment]
> 1.2.1 has an annoying screensharing issue for some people, if we see this also happens to you I can try to do a 1.11.6 release with your changes.

Could be a similar recent screen sharing issue like this one (specifically only present on MS Edge): https://learn.microsoft.com/en-au/answers/questions/2120532/screen-sharing-stops-working-(ms-teams-google-meet

So I guess, the issue is caused by changes on MS side. Either in the Teams PWA or in how it's rendered in Edge. News is for me, that the Electron rendering teams-for-linux is using seems also affected. This info could help in identifying the regression location. Not sure where to address this, though.

**Comment by IsmaelMartinez** [comment]
Might be unrelated as electron uses chromium on the back. I don't remember
if Edge is a chromium based browser or not, I think so, but with a lot of
MS tweaks?!? thanks for sharing and checking.

**Comment by IsmaelMartinez** [comment]
https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.12.2 is pre release ready.

**Comment by nsballmann** [comment]
> Might be unrelated as electron uses chromium on the back. I don't remember if Edge is a chromium based browser or not, I think so, but with a lot of MS tweaks?!? thanks for sharing and checking.

MS Edge is definitely Chromium based. So it might be a regression of the Teams PWA even with all Chromium based software?

The time based coincidence is just striking.

**Comment by IsmaelMartinez** [comment]
It does seem to be a chromium issue https://github.com/IsmaelMartinez/teams-for-linux/issues/1489#issuecomment-2507456547 but the fix is in version 131, what probably means we need to wait until electron 34 is out of beta (and a bit stable) and hopefully they will have the fix there :/

**Pull request merged**
