### PR TITLE
Fix depshield issues

### LINKED ISSUE #246: [DepShield] (CVSS 7.4) Vulnerability due to usage of lodash.isempty:4.4.0
**Vulnerabilities**

DepShield reports that this application's usage of [lodash.isempty:4.4.0](https://ossindex.sonatype.org/component/pkg:npm/lodash.isempty@4.4.0) results in the following vulnerability(s):

- (CVSS **7.4**) [CWE-471: Modification of Assumed-Immutable Data (MAID)](https://ossindex.sonatype.org/vuln/0f23ff35-235f-404f-8118-bc1580673fd0)

<hr />

**Occurrences**

lodash.isempty:4.4.0 is a transitive dependency introduced by the following direct dependency(s):

• **[electron-editor-context-menu:1.1.1](https://ossindex.sonatype.org/component/pkg:npm/electron-editor-context-menu@1.1.1)**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└─ [lodash.isempty:4.4.0](https://ossindex.sonatype.org/component/pkg:npm/lodash.isempty@4.4.0)

<sub>This is an automated GitHub Issue created by Sonatype DepShield. Details on managing GitHub Apps, including DepShield, are available for [personal](https://help.github.com/articles/managing-your-personal-account-s-apps/) and [organization](https://help.github.com/articles/managing-your-organization-s-apps/) accounts. Please submit questions or feedback about DepShield to the [Sonatype DepShield Community](https://community.sonatype.com/c/depshield).</sub>

### PR DESCRIPTION
**Pull request by IsmaelMartinez**
This should fix #246, #247, #248 and #249.

### CODE REVIEW

**Comment by byteSamurai** [comment]
Wait a moment: 
I took a look on #248 as well but DeepCode was actually complaining about using not up2date lodash.
So: Why is is fixed by forking electron-editor-context-menu and increase its version to 1.1.2? Makes not sense to me :thinking: 

Cloud you explain it to me? I am kind of confused.

(Despite that: Is it intended to have a different version in the [lock file](https://github.com/IsmaelMartinez/electron-editor-context-menu/blob/master/package-lock.json#L3) than in the package.json?)

**Comment by IsmaelMartinez** [comment]
Hi @byteSamurai, You are right and I am still getting use to this depshild stuff. 

I will reopen the issues, revert the changes and leave it to you ;) 

I am tempted to use https://snyk.io/ instead as it tell you what the remediation is.

**Comment by byteSamurai** [comment]
That escalated quickly :smile: 
Sure, gimme gimme. 

> I am tempted to use https://snyk.io/ instead as it tell you what the remediation is.

Then lets use this please. As we are not sure what MS is coming up with, we should fix issues in a least time consuming way, imho.
DeepCode was...confusing for me. Or I didn't get it at all.

**Comment by IsmaelMartinez** [comment]
I just reverted this in #258. Not sure what is going on with the branches. I will disable DepShield as is annoying. I will try to add snyk next. ;) sort of related to #251

**Comment by IsmaelMartinez** [comment]
And thanks for looking into these things! probably assign it to yourself so other people don't do the job while you are doing it!

**Comment by byteSamurai** [comment]
> probably assign it to yourself so other people don't do the job while you are doing it!
I am almost sure I have no privileges for it:
image

Am I wrong?

**Comment by IsmaelMartinez** [comment]
let me give you more rights.

**Comment by IsmaelMartinez** [comment]
looks like snyk says we are safe... feel free to investigate further if you wish but I think those issues can now be close and we can forget about depshield stuff.

and now you are a contributor ;) congratulations

**Comment by byteSamurai** [comment]
> looks like snyk says we are safe... feel free to investigate further if you wish but I think those issues can now be close and we can forget about depshield stuff.
:+1: 

> and now you are a contributor ;) congratulations
:tada:

**Pull request merged**
