### PR TITLE
Add --minimized option to start app in tray

### PR DESCRIPTION
**Pull request by didster**

### CODE REVIEW

**Comment by IsmaelMartinez** [comment]
Thanks a lot for contributing!! 

The only last change needed is to update the readme file in the config folder. It should the same info.

This solves #27 that was close due inactivity. Thanks again!!

**Comment by didster** [comment]
Happy to help - with MS moving our corp O365 accounts from Skype For Business and forcing teams on us, I can no longer use faithful old Pidgin with the office communicator plugin so I stumbled on your app today looking for a Linux client.  The only thing missing was that, so I decided to add it.

The change should be there to README.md now.

**Comment by didster** [comment]
Sorry I think I miss read you - it looks like we both did it!  Oh well

**Comment by IsmaelMartinez** [comment]
Didn't change anything from my side. I will review it next week
I am currently offline and can't test this things even if I want.

**Comment by IsmaelMartinez** [comment]
merged. Thanks again!

**Pull request merged**
