### PR TITLE
Fix #1033

### LINKED ISSUE #1033: Missing "Meeting started" notifications
**Describe the bug**
Sometime I am missing "Meeting started" notifications. After debugging I saw that some calendarEvents don't have a skypeTeamsData attibute, making addEligibleCalendarEvents raise an exception an miss some event that would have created a notification

I'm going to propose a PR
**To Reproduce**
Have a calendarEvent without skypeTeamsData (probably beacausit's not a teams meeting)
Have another meeting with skypeTeamsData

Wait for the teams meeting to start

**Expected behavior**
"Meeting started" notification should appear

**Desktop (please complete the following information):**
 - OS: Ubuntu22
 - Installation package AppImage
 - Version 1.3.23

### PR DESCRIPTION
**Pull request by julaudo**
Ignore calendarEvents without skypeTeamsData
Fixes #1033

### CODE REVIEW

**Comment by IsmaelMartinez** [comment]
thanks for contributing, can you increase the version number in the package.json file to the next lower version? https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/package.json#L3 (to 1.3.25)

We really odd to automate that part somehow as people always forgets. Thanks a lot again for the contribution!

**Comment by julaudo** [comment]
I added a commit and rebased onto develop

**Review by IsmaelMartinez — APPROVED** [review]

**Comment by IsmaelMartinez** [comment]
Thanks for contributing! I will release this next.

**Comment by IsmaelMartinez** [comment]
Released! Thanks again! https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.3.25

**Pull request merged**
