### PR TITLE
#591 Add forceBackground Option to use a custom meeting background

### PR DESCRIPTION
**Pull request by amenk**
See #591 

How to use

* supply the `--forceBackground /path/to/your/jpeg/our/png/file.png` option
* when starting a meeting, choose any background image

The previews are not replaced, but the meeting background is working

Thanks to @jijojosephk

### CODE REVIEW

**Comment by amenk** [comment]
More or less a draft, but it's basically working.
Maybe it can even be merged as experimental?

**Comment by amenk** [comment]
Ready - I mean it would be nicer, to also replace the previews and make this reachable via GUI, but it's marked as experimental, so it would be okay?

**Comment by jijojosephk** [comment]
Thanks @amenk. Could you please bump the version also in package.json?

**Comment by amenk** [comment]
1.0.84

Or 1.1.0 ?

If semver is used, 1.1.0 would be right cause it's a feature?

**Comment by jijojosephk** [comment]
> 1.0.84
> 
> Or 1.1.0 ?
> 
> If semver is used, 1.1.0 would be right cause it's a feature?

Currently what's followed is incrementing the last digit. Let's ask @IsmaelMartinez what could be the versioning strategy going forward. Shall we make it `1.0.84` for now? Thanks for the PR. We'd release it as experimental build.

**Comment by jijojosephk** [comment]
I re-opened #462. Let's discuss about the implementation of GUI.

**Comment by IsmaelMartinez** [comment]
Happy with 1.1.0. 

We did stop using semver when MS started supporting Linux, as their app was version 1.2.0 (or 1.3.0). That was to avoid confusion as many people came here and reported their app issues. 

Now that there is no MS app, it will be good to go back to semver.

**Comment by jijojosephk** [comment]
May be we can move to `1.1.0` when this is released as a new feature. Probably with #462 because the current one is experimental. So the users can experiment and report bugs.

**Comment by jijojosephk** [comment]
```js
injector = angular.element(document).injector();
const cvbs = injector.get('customVideoBackgroundsService');
// We need to override the function below and add custom images to the array it returns.
cvbs.getProvidedImagesFromCdn();

```

That would help listing the custom images in the preview.

**Comment by amenk** [comment]
Seems not 100% reliable. in the morning I was having an old background image, restarting teams gave me the configured one

**Comment by jijojosephk** [comment]
> Seems not 100% reliable. in the morning I was having an old background image, restarting teams gave me the configured one

Most likely cache. Like I said, we can experiment with this.

**Comment by jijojosephk** [comment]
@amenk I'm abandoning this as we have a different implementation. Thanks for your effort!

**Pull request closed without merging**
