### PR TITLE
index.js: Add env variable to prefer wayland over xwayland

### PR DESCRIPTION
**Pull request by philschenker**
This likely solves https://github.com/IsmaelMartinez/teams-for-linux/issues/1331

However it is not yet tested

### CODE REVIEW

**Comment by IsmaelMartinez** [comment]
Thanks for this fix! If you can increase the version number of the package.json and add line to the appdata.xml that would be then ready for release.  

Process is detailed here:
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/CONTRIBUTING.md#release-process

**Comment by philschenker** [comment]
This seems to not work yet. Need to look into it again at some other point

**Comment by IsmaelMartinez** [comment]
This seems to be an old electron issue https://github.com/electron/electron/pull/35630. 

It looks like you did increased the version but another PR was merged just before. Remember to pull 1st. The conflict should be easy to solve. 

Thanks!

**Comment by philschenker** [comment]
I will close this PR. This issue seems to be limited to Ubuntu. After the upgrade 22.04 -> 24.04 of Ubuntu it broke my system horribly so I switched to another Distro. There this flatpak works like a charm

**Pull request closed without merging**
