### PR TITLE
Fix for wayland screenshare including system audio.

### PR DESCRIPTION
**Pull request by herbiejhopkins**
Fix an issue with my previous change regarding wayland source selection. Should have tested that more thoroughly.

This issue is also mentioned in #1065

### CODE REVIEW

**Comment by NaimadTheOne** [comment]
I'm looking forward to the release. When will it be out?

**Comment by IsmaelMartinez** [comment]
need to wait for 1.4.4 to be tested (in the process) then I will release this as a pre-release. Maybe tomorrow...

**Comment by jijojosephk** [comment]
@herbiejhopkins if possible, we can have an option to disable system audio sharing. I guess currently it is hard coded. Isn't it?

**Comment by herbiejhopkins** [comment]
@jijojosephk See comment in #911

**Comment by eprudspk** [comment]
This caused my microphone sound to be duplicated when doing a screenshare. It seems the second chromium sound input that is created is automatically connected with my microphone, at least on KDE plasma 5.27.10. 

It's annoying because, every single time I have to share my screen, I also have to open `qpwgraph` and disconnect one of the inputs.

**Pull request merged**
