### PR TITLE
changing ms teams icons as they are trademarked

### PR DESCRIPTION
**Pull request by IsmaelMartinez**
changing ms teams icons as they are trademarked.

Special thanks to @nursoda, @le-patenteux and all people that was involved on this. From the providing ideas, voting, comments, etc.

I hope you like the new icons.

### CODE REVIEW

**Comment by yermulnik** [comment]
> I hope you like the new icons.

They look marvelous 😍

**Comment by guillaume-mueller** [comment]
Sorry but I dislike the penguin. Only the `T` in square would be very better.

**Comment by nursoda** [comment]
> Sorry but I dislike the penguin. Only the `T` in square would be very better.

Seeing it in the start menu and taskbar, I agree.

**Comment by IsmaelMartinez** [comment]
Hi @guillaume-mueller/@nursoda , thanks for the feedback. Unfortunately I don't think I am going to be changing that icon in the short time. 

However, if you prefer another icon you can just use the appIcon config option. This was mostly driven to get of the trademark issue in flathub/MS.

I think it would be good to move the notification number out of the penguin face (to the bottom left maybe?), but I got little time available.  Been honest, answering to comments take most of my free time.

**Comment by IsmaelMartinez** [comment]
Hi @guillaume-mueller / @nursoda , thanks for the feedback. Unfortunately I don't think I am going to be changing that icon in the short time. 

However, if you prefer another icon you can just use the appIcon config option. This was mostly driven to get of the trademark issue in flathub/MS.

I think it would be good to move the notification number out of the penguin face (to the bottom left maybe?), but I got little time available.  Been honest, answering to comments take most of my free time.

**Comment by yermulnik** [comment]
> Sorry but I dislike the penguin. Only the `T` in square would be very better.

My 2c: it's «**T**eams for **Linux**», rather than just «**T**eams» I guess.
ℹ️ Tux (rather than «penguin») is official Linux mascot.
I see `T` in combination with Tux as a match for this projects name.

**Comment by guillaume-mueller** [comment]
I'm sorry I talked a bit too shortly.

Actually for the program icon, I think it's OK.

But for the taskbar I think it's not nice like the T in square is uncentered and the Tux is kind of detailed while tiny.

**Comment by tstackhouse** [comment]
I can't say I'm in favor of this at all.  It would be nice to at least have the option to change this logo back, or only have this change affect the Flatpak build (I'll withhold my Opinions about Flatpak/Snaps, but I think it's obvious)

**Comment by IsmaelMartinez** [comment]
@tstackhouse and @guillaume-mueller , I am not a layer but the icon is trademarked and I can't distribute it. You can use the appIcon config option if you want to use a different icon. 

No idea about 'Microsoft Teams' appearing on the hovered by the mouse, that wasn't part of the complains by MS and Flathub. I just don't want to be stuck on a legal process and for this app to be banned, just for the sake of an icon.

**Comment by tstackhouse** [comment]
@IsmaelMartinez I wasn't aware that there was a complaint from MS involved, I thought it was just FlatHub being nitpicky. I've changed the icon in my local `.desktop` file, but that doesn't affect the app itself.  Where is the `appIcon` config?  Is it a CLI switch?

**Comment by IsmaelMartinez** [comment]
Hey, is an config https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config (I believe is called `appIcon`

**Comment by tstackhouse** [comment]
Got it.  Thanks.  And again, thanks for making this app to begin with, it's very handy to have a dedicated app for Teams rather than having to keep a browser window open somewhere, or rely on the seemingly abandoned Teams for Linux Beta from MS.

Looking into it, if the app could also support an `--icon` switch, in addition to (or instead of) `--appIcon`, then the .desktop entry could be updated to include `%i` to use the icon specified in the .desktop file, from what I found in the [FreeDesktop.org docs](https://specifications.freedesktop.org/desktop-entry-spec/latest/exec-variables.html).

**Comment by IsmaelMartinez** [comment]
we can make it an alias. I haven't done that yet but it should be possible https://yargs.js.org/docs/#api-reference-aliaskey-alias

**Pull request merged**
